#Eureka服务配置
eureka:
  client:
    register-with-eureka: true #当前服务是否将自己注册到Eureka服务中，如果本身就是Eureka,会自动注册到自己中
    fetch-registry: true #是否从Eureka中获取注册信息
    service-url: #Eureka客户端与Eureka服务端进行交互的地址
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ip-address}:${spring.application.name}:${server.port}
    #ip-address:
nickName: world all  the men  love 2020 /这是我们的测试  bingbingbing
spring:
  #设置http编码
  http:
    encoding:
      force: true
      charset: utf-8
      enabled: true
logging:
  level:
    org:
      springframework: debug
#启用/ restart端点重新启动应用程序上下文 刷新配置
endpoints:
  refresh:
    enabled: true